
package novoEmail.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.2
 * Wed Jan 27 17:43:24 BRT 2021
 * Generated source version: 3.4.2
 */

@XmlRootElement(name = "validarEmailAddress", namespace = "http://novoEmail/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validarEmailAddress", namespace = "http://novoEmail/")

public class ValidarEmailAddress {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

